# Generated by Django 4.2 on 2023-04-25 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('category', models.CharField(choices=[('FA', 'Fashion'), ('FU', 'Furniture'), ('EL', 'Electronics'), ('MI', 'Miscellaneous'), ('KI', 'Kitchen'), ('DE', 'Decor'), ('SP', 'Sports'), ('TO', 'Toys'), ('HO', 'Home & Garden'), ('OT', 'Other')], default='Decor', max_length=2)),
                ('bids', models.ManyToManyField(blank=True, related_name='bids', to='auctions.bids')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
