# Generated by Django 4.2 on 2023-04-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_description_alter_listing_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_created',
        ),
    ]
