# Generated by Django 4.2 on 2023-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('FU', 'Furniture'), ('EL', 'Electronics'), ('MI', 'Miscellaneous'), ('KI', 'Kitchen'), ('DE', 'Decor'), ('SP', 'Sports'), ('TO', 'Toys'), ('HO', 'Home & Garden'), ('OT', 'Other')], default='DE', max_length=2),
        ),
    ]
